"""Agent discovery. Public, unauthenticated, machine-parseable.

An autonomous buyer arrives knowing nothing. It needs, in this order: what this
service sells, how to call it, how to pay, and what comes back. That is
`/llms.txt` (the map), `/agent-guide` (the prose), `/openapi.json` (the
contract, generated by FastAPI from the code) and `/v1/agent/info` (the live
payment parameters).

Payment values are served here rather than baked into the static files because
a wallet address and a price change; a checked-in copy of them would go stale
silently and send an agent's USDC to the wrong address. `/v1/agent/info`
deliberately mirrors the vocabulary of the 402 challenge in
`x402_middleware.payment_required_response`, so discovery and rejection speak
the same language.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse
from pydantic import BaseModel, ConfigDict, Field

from app.services import x402
from app.services.agent_offer import payment_terms
from app.services.x402_middleware import CREDIT_PRICE_BASE_UNITS, PAYMENT_HEADER

router = APIRouter(tags=["agent-discovery"])

PUBLIC_DIR = Path(__file__).resolve().parents[3] / "public"

LLMS_TXT = PUBLIC_DIR / "llms.txt"
AGENT_GUIDE = PUBLIC_DIR / "agent-guide.md"


class NetworkInfo(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    usdc_contract: str
    is_testnet: bool
    accepted: bool = Field(
        description="False means a payment on this network will be refused."
    )
    note: Optional[str] = None


class AgentInfoResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    service: str
    description: str
    docs: Dict[str, str]
    auth_methods: List[Dict[str, Any]]
    payment: Dict[str, Any]
    networks: List[NetworkInfo]
    endpoints: List[Dict[str, str]]


def _networks() -> List[NetworkInfo]:
    """Every network we know, each saying plainly whether it is accepted.

    base-mainnet is listed because an agent will otherwise ask, and answering
    "unknown network" would be misleading — we know it, we refuse it.
    `x402.assert_testnet` turns a mainnet payment into an error, and AGENTS.md
    forbids mainnet custody. Advertising it as supported would take real USDC
    for a call that then fails.
    """
    out = []
    for name, network in sorted(x402.NETWORKS.items()):
        accepted = network.is_testnet
        out.append(
            NetworkInfo(
                name=name,
                usdc_contract=network.usdc_contract,
                is_testnet=network.is_testnet,
                accepted=accepted,
                note=(
                    None
                    if accepted
                    else "Known but NOT accepted: this deployment is testnet only. "
                    "A payment on this network will be refused and not refunded "
                    "by us. Do not send funds here."
                ),
            )
        )
    return out


def _payment_block() -> Dict[str, Any]:
    """Live payment parameters, shaped like the 402 challenge's `accepts` entry.

    Lives in app/services/agent_offer.py so the outreach drafts attach the
    identical terms rather than restating them.
    """
    return payment_terms()


@router.get(
    "/v1/agent/info",
    response_model=AgentInfoResponse,
    summary="Machine-readable service, auth and payment description",
)
async def agent_info() -> AgentInfoResponse:
    """Everything a buying agent needs, as JSON. No auth, no signup."""
    return AgentInfoResponse(
        service="ImportAlpha Lite",
        description=(
            "China-to-US product sourcing intelligence. Given a product or a "
            "category, returns an opportunity score, a China unit-cost range, "
            "landed cost, margin, a competition signal and risk flags, with "
            "source_url, observed_at and confidence on every datapoint."
        ),
        docs={
            "llms_txt": "/llms.txt",
            "agent_guide": "/agent-guide",
            "openapi": "/openapi.json",
            "interactive": "/docs",
        },
        auth_methods=[
            {
                "method": "api_key",
                "header": "Authorization",
                "format": "Bearer <key>",
                "how_to_obtain": "Contact the operator; keys are issued manually.",
                "billing": "Draws on a prepaid credit balance bought with a card.",
            },
            {
                "method": "x402",
                "header": PAYMENT_HEADER,
                "format": "<transaction hash of a USDC transfer>",
                "how_to_obtain": "No signup. Pay on-chain, then send the hash.",
                "billing": "One verified transfer grants one credit.",
                "precedence": (
                    "An Authorization header always wins. Sending both means the "
                    "payment is ignored, not double-spent."
                ),
            },
        ],
        payment=_payment_block(),
        networks=_networks(),
        endpoints=[
            {"method": "GET", "path": "/v1/opportunities", "auth": "required",
             "description": "Scored product opportunities for a category."},
            {"method": "POST", "path": "/v1/landed-cost", "auth": "required",
             "description": "Landed cost for a unit cost, weight and quantity."},
            {"method": "POST", "path": "/v1/reports", "auth": "required, 1 credit",
             "description": "Request a report. Returns 202 with a report_id."},
            {"method": "GET", "path": "/v1/reports/{report_id}", "auth": "required",
             "description": "Poll a requested report."},
            {"method": "GET", "path": "/v1/public/sample-reports", "auth": "none",
             "description": "Three synthetic specimen reports."},
            {"method": "GET", "path": "/v1/public/pricing", "auth": "none",
             "description": "Card pricing tiers."},
            {"method": "GET", "path": "/health", "auth": "none",
             "description": "Version, uptime and dependency state."},
        ],
    )


def _serve(path: Path, media_type: str) -> FileResponse:
    if not path.is_file():
        # Shipped in the image, so absence is a packaging fault, not a 404 the
        # caller can do anything about — but it must not surface as a 500.
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"{path.name} is missing from this deployment.",
        )
    return FileResponse(path, media_type=media_type)


# GET and HEAD on all of these. Crawlers and agents probe with HEAD to check a
# document exists and what type it is before fetching it, and the StaticFiles
# mount at "/" answers 404 for any method the API routes decline — so without
# HEAD declared, a probing agent is told the manifest does not exist and stops
# discovering. These are out of the schema already, so the two methods cannot
# collide on an operation_id the way a documented route's would.
@router.api_route("/llms.txt", methods=["GET", "HEAD"], include_in_schema=False)
async def llms_txt() -> FileResponse:
    """The llms.txt manifest. text/plain so an agent does not have to sniff it."""
    return _serve(LLMS_TXT, "text/plain; charset=utf-8")


@router.api_route("/agent-guide", methods=["GET", "HEAD"], include_in_schema=False)
async def agent_guide() -> FileResponse:
    """The long-form guide, as markdown rather than a rendered page."""
    return _serve(AGENT_GUIDE, "text/markdown; charset=utf-8")


@router.head("/v1/agent/info", include_in_schema=False)
async def agent_info_head() -> AgentInfoResponse:
    """Hidden twin of the GET, for the same probing reason."""
    return await agent_info()
