"""add account_id to reports

Revision ID: 456aca293990
Revises: f2c00b0a0a6e
Create Date: 2026-09-22 20:20:27.436658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456aca293990'
down_revision: Union[str, Sequence[str], None] = 'f2c00b0a0a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add reports.account_id so a failed report can be refunded.

    Three steps, not one. Adding a NOT NULL column with no default fails
    outright on a table that already has rows, and this one did — 11 reports
    predate the column. So: add it nullable, backfill, then constrain it.

    Rows written before billing existed are stamped with a sentinel rather
    than a real account. They cannot be refunded (nobody was charged), and
    LEGACY_ACCOUNT_ID in app/services/report_store.py is the matching constant
    the refund path checks. The literal is repeated here on purpose — a
    migration must keep working when the application constant moves.
    """
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.String(length=64), nullable=True))

    op.execute(
        "UPDATE reports SET account_id = 'legacy-unknown' WHERE account_id IS NULL"
    )

    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.alter_column("account_id", existing_type=sa.String(length=64), nullable=False)
        batch_op.create_index("ix_reports_account_id", ["account_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_account_id')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
