"""add credit_transactions ledger

Revision ID: 6c23c0d74c9b
Revises: 456aca293990
Create Date: 2026-09-22 20:31:58.994972

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c23c0d74c9b'
down_revision: Union[str, Sequence[str], None] = '456aca293990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the append-only ledger and seed it from existing balances.

    The table creation is as autogenerated. The backfill below is not, and is
    the reason this file was edited before being applied: accounts already
    exist with non-zero balances and no ledger rows behind them. Without an
    opening entry, `reconcile()` would report every pre-existing account as
    corrupt on day one — cached balance N against SUM(delta) 0.

    Each such account gets one `adjustment` row carrying its whole balance,
    referenced as a pre-ledger opening balance. It is honest about what it is:
    we cannot reconstruct the history that produced those credits, only state
    the point the ledger starts from.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_credit_transactions_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_credit_transactions_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###

    # --- data migration: opening balances -------------------------------
    connection = op.get_bind()
    accounts = connection.execute(
        sa.text("SELECT account_id, balance, created_at FROM credit_accounts")
    ).fetchall()

    for account_id, balance, created_at in accounts:
        if not balance:
            # A zero balance needs no opening entry: SUM over no rows is 0,
            # which already reconciles.
            continue
        connection.execute(
            sa.text(
                "INSERT INTO credit_transactions "
                "(id, account_id, delta, reason, reference, balance_after, created_at) "
                "VALUES (:id, :account_id, :delta, 'adjustment', "
                ":reference, :balance_after, :created_at)"
            ),
            {
                "id": f"T-{uuid.uuid4().hex[:12]}",
                "account_id": account_id,
                "delta": balance,
                "reference": "pre-ledger opening balance",
                "balance_after": balance,
                "created_at": created_at,
            },
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_transactions_created_at')
        batch_op.drop_index('ix_credit_transactions_account_id')

    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
