"""unique purchase reference

Revision ID: e8cad44c3fec
Revises: 6c23c0d74c9b
Create Date: 2026-09-22 20:55:19.677139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cad44c3fec'
down_revision: Union[str, Sequence[str], None] = '6c23c0d74c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """One purchase per payment event, enforced by the database.

    Hand-written, not autogenerated: this is a *partial* unique index, which
    Alembic's autogenerate does not emit.

    Checking for an existing row before inserting is not enough on SQLite. A
    write lock is only taken at the first write, so two concurrent webhook
    deliveries both run their SELECT, both see nothing, and both insert —
    verified, and it credited an account four times for one event. The
    constraint makes the duplicate impossible rather than unlikely.

    It is partial because only purchases carry a globally unique reference: a
    topup's reference is a free-text note and may legitimately repeat.
    """
    op.create_index(
        "uq_credit_transactions_purchase_reference",
        "credit_transactions",
        ["reference"],
        unique=True,
        sqlite_where=sa.text("reason = 'purchase' AND reference IS NOT NULL"),
        postgresql_where=sa.text("reason = 'purchase' AND reference IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "uq_credit_transactions_purchase_reference",
        table_name="credit_transactions",
    )
